FROM dxflrs/garage:v2.3.0 AS garage

FROM alpine:3.22
COPY --from=garage /garage /usr/local/bin/garage
COPY bootstrap.sh /usr/local/bin/bootstrap-garage
RUN chmod +x /usr/local/bin/bootstrap-garage
ENTRYPOINT ["/usr/local/bin/bootstrap-garage"]
